Repository moment/moment, pull requests merged in 2018-03, with the labels that each got.

#3896 [new locale] tg: Tajik (Tajikistan) locale
  component.json
  src/locale/tg.js
  src/test/locale/tg.js
Labels: Pending Next Release

#4085 [misc] Print console warning when setting non-existent locales
  src/lib/locale/locales.js
Labels: Docs written, Pending Next Release

#4101 [locale] tet: Improvements for month and weekday names
  src/locale/tet.js
  src/test/locale/tet.js
Labels: Pending Next Release

#4140 [locale] kn: Improve short months
  src/locale/kn.js
  src/test/locale/kn.js
Labels: Pending Next Release

#4184 [locale] id: Fix short name for august in id locale
  src/locale/id.js
  src/test/locale/id.js
Labels: Language, Pending Next Release

#4195 [locale] pt-br: Simplify pt-br past relativeTime
  src/locale/pt-br.js
  src/test/locale/pt-br.js
Labels: Pending Next Release

#4310 [bugfix] Fix #3883 lazy load parentLocale in defineLocale, fallback to global if missing
  src/lib/locale/locales.js
  src/test/moment/locale_inheritance.js
Labels: Docs written, Pending Next Release

#4360 [bugfix] Correct min/max TypeScript signatures
  moment.d.ts
  typing-tests/moment-tests.ts
Labels: Pending Next Release

#4361 [bugfix] remove `ordinal` for `Turkish` locale as they use `cardin…
  src/locale/tr.js
  src/test/locale/tr.js
Labels: Pending Next Release

#4372 [new locale] ug-cn: Added locale ug-cn
  src/locale/ug-cn.js
  src/test/locale/ug-cn.js
Labels: Pending Next Release

#4379 [locale] ko: Add trailing dot to L and l
  src/locale/ko.js
  src/test/locale/ko.js
Labels: Pending Next Release

#4391 [bugfix] Fix #4390: use offset properly in toISOString
  src/lib/moment/format.js
Labels: Pending Next Release

#4463 [misc] Update downloads badge to point to graph of downloads 📈
  README.md
Labels: Discussion

#4430 [locale] Fix zh-tw locale
  src/locale/zh-tw.js
  src/test/locale/zh-tw.js
Labels: locale approval needed
