Repository moment/moment, pull requests merged in 2019-01, with the labels that each got.

#4849 [bugfix] locale/en-ie.js date format
  src/locale/en-ie.js
  src/test/locale/en-ie.js
Labels: Pending Next Release

#4377 [locale] es-us: Update month parsing to be dot lenient
  src/locale/es-us.js
  src/test/locale/es-us.js
Labels: Pending Next Release

#4338 [bugfix] Fix startOf/endOf DST issues while boosting performance
  src/lib/create/date-from-array.js
  src/lib/moment/start-end-of.js
  src/test/moment/start_end_of.js
Labels: Needs Revision, Pending Next Release

#4771 [locale] Extend cs locale with name of the months in genitive
  src/locale/cs.js
  src/test/locale/cs.js
Labels: Pending Next Release

#4682 [locale] fo: Fixed relativeTimes for m and M (#4609)
  src/locale/fo.js
  src/test/locale/fo.js
Labels: Pending Next Release

#4957 [new locale] (oc-lnc) Occitan
  src/locale/oc-lnc.js
  src/test/locale/oc-lnc.js
Labels: locale approval needed

#4560 [locale] es: Add es translation for invalidDate
  src/locale/es.js
  src/test/locale/es.js
Labels: locale approval needed
