Repository moment/moment, pull requests merged in 2020-04, with the labels that each got.

#5206 [locale] Fix incorrect Slovak translation "za" -> "o"
  src/locale/sk.js
  src/test/locale/sk.js
Labels: Pending Next Release

#5279 [locale] (ka) georgian locale fixes
  src/locale/ka.js
  src/test/locale/ka.js
Labels: Pending Next Release

#5356 [new locale] (zh-mo) Add Chinese Macau
  src/locale/zh-mo.js
  src/test/locale/zh-mo.js
Labels: Pending Next Release

#5387 [locale] (ro) Fixed month abbreviation for February
  src/locale/ro.js
  src/test/locale/ro.js
Labels: Pending Next Release, locale approval needed

#5445 [locale] Correct swedish ordinals
  src/locale/sv.js
  src/test/locale/sv.js
Labels: locale approval needed

#5427 [locale] ar-ma, fix a typo in monday's name
  src/locale/ar-ma.js
  src/test/locale/ar-ma.js
Labels: locale approval needed

#4470 [feature] add support for [YYYY] as ISO8601 format
  src/lib/create/from-string.js
  src/test/moment/create.js
Labels: Docs written, Needs tests

#3666 [feature] Calendar function handles formats only arg
  src/lib/moment/calendar.js
  src/lib/utils/is-calendar-spec.js
  src/lib/utils/is-moment-input.js
  src/lib/utils/is-string.js
  src/test/moment/calendar.js
Labels: Needs Revision, Needs docs, Needs tests

#3846 [bugfix] Change 'Y' format token to adhere to ISO under 9999, fixes #3842
  src/lib/units/year.js
  src/test/moment/format.js
Labels: Breaking change

#4368 [locale] Update bo locale
  src/locale/bo.js
  src/test/locale/bo.js
Labels: locale approval needed
