Repository moment/moment, pull requests merged in 2020-09, with the labels that each got.

#5574 [bugfix] More complete type definitions for strict formatless parsing #4611
  moment.d.ts
  ts3.1-typing-tests/moment-tests.ts
  ts3.1-typings/moment.d.ts
Labels: Help Wanted

#5661 [locale] (pt-br) add invalid date translation
  src/locale/pt-br.js
Labels: Discussion

#4742 [locale] sr-cyrl: Improve L* formats
  src/locale/sr-cyrl.js
  src/locale/sr.js
  src/test/locale/sr-cyrl.js
  src/test/locale/sr.js
Labels: locale approval needed

#5666 [locale] tg-TJ: Improve months and date formats
  src/locale/tg.js
  src/test/locale/tg.js
Labels: Discussion

#5611 [misc] update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Discussion
